TELESCOPE_IP: '10.211.55.3:11111'
TELESCOPE_DEVICE_NUMBER: 0
FOCUSER_IP: '10.211.55.3:11111'
FOCUSER_DEVICE_NUMBER: 0
TRACKING_ERROR: False # simulate tracking error
TMASS: False    # use 2MASS crossmatched catalog, else uses Gaia RP photometry
FLATS: False   # simulate flat fielding
CAMERA:
  name: "test-gaia-cam"
  width: 1024 # [pixels]
  height: 1280 # [pixels]
  bin_x: 1 # not used
  bin_y: 1 # not used
  pitch: 12 # [microns]
  max_adu: 16000 # [ADU]
  well_depth: 55000 #[e-]
  bias: 3000 # [ADU]
  gain: 5 # [e-/ADU]
  read_noise: 90 # [e-]
  dark_current: 150 # [e-/s]
  average_quantum_efficiency: 0.6 # average qe (after inefficiencies of telescope/filters) [0-1]
SITE:
  sky_background: 1000 # e-/m2/arcsec2/s
  seeing: 1.5 # [arcsec]
FOCUSER:
  sharp_pos: 10000 # [steps]
  blurred_offset: 100 # when 2x seeing begins: seeing * ( 1 + np.abs(focuser.Position - config['FOCUSER']['sharp_pos'])/config['FOCUSER']['blurred_offset'] ) [steps]


