TELESCOPE_IP: '10.211.55.3:11111'
TELESCOPE_DEVICE_NUMBER: 0
TRACKING_ERROR: False # simulate tracking error
TMASS: False    # use 2MASS crossmatched catalog, else uses Gaia RP photometry
LOCAL_DB: False # use local database (see https://github.com/ppp-one/gaia-tmass-sqlite)
LOCAL_DB_PATH: 'pointing.db'
FLATS: False   # simulate flat fielding
CAMERA:
  width: 2048 # [pixels]
  height: 2048 # [pixels]
  plate_scale: 0.35 # [arcsec/pixel]
  pitch: 12 # [microns]
  welldepth: 65535 #[e-]
  maxadu: 65535 # [ADU]
  bias: 300 # [ADU]
  gain: 1.0 # [e-/ADU]
  readnoise: 6.2 # [e-]
  darkcurrent: 0.2 # [e-/s]
  skybackground: 15 # [e]
  qe: 0.6 # average qe (after inefficiencies of telescope/filters) [0-1]
  collecting_area: 0.7 # effective telescope collecting area (could get from telescope driver, but decided not.) [m^2]


