# Coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # Noqa: F401

import re  # Noqa: F401
from typing import Any, Dict, List, Optional  # Noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # Noqa: F401


class DeviceTypeDeviceNumberCommandblindPutRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DeviceTypeDeviceNumberCommandblindPutRequest - a model defined in OpenAPI

        Command: The command of this DeviceTypeDeviceNumberCommandblindPutRequest.
        Raw: The raw of this DeviceTypeDeviceNumberCommandblindPutRequest.
        ClientID: The client_id of this DeviceTypeDeviceNumberCommandblindPutRequest [Optional].
        ClientTransactionID: The client_transaction_id of this DeviceTypeDeviceNumberCommandblindPutRequest [Optional].
    """

    Command: str = Field(alias="Command")
    Raw: str = Field(alias="Raw")
    ClientID: Optional[int] = Field(alias="ClientID", default=None)
    ClientTransactionID: Optional[int] = Field(alias="ClientTransactionID", default=None)

    @validator("ClientID")
    def client_id_max(cls, value):
        assert value <= 4294967295
        return value

    @validator("ClientID")
    def client_id_min(cls, value):
        assert value >= 0
        return value

    @validator("ClientTransactionID")
    def client_transaction_id_max(cls, value):
        assert value <= 4294967295
        return value

    @validator("ClientTransactionID")
    def client_transaction_id_min(cls, value):
        assert value >= 0
        return value

DeviceTypeDeviceNumberCommandblindPutRequest.update_forward_refs()
